modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\modules\admin\models\LoginForm;
use app\modules\admin\models\User;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'dashboard'],
                'rules' => [
                    [
                        'actions' => ['logout', 'dashboard'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex() {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['psa/index']);
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['psa/index']);
        }
        return $this->render('index', ['model' => $model]);
    }

    public function actionDashboard() {
        return $this->render('dashboard');
    }
    
    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->redirect(['@web/../..']);
    }

}

modules/admin/controllers/PsaController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\modules\admin\models\LoginForm;
use app\modules\admin\models\Disciplina;
use app\modules\admin\models\DisciplinaSearch;

/**
 * Default controller for the `admin` module
 */
class PsaController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex() {
        $this->layout = '@app/views/layouts/dashboard.php';
        $user = \Yii::$app->user->identity;
        
        $searchModel = new DisciplinaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        
        return $this->render('index',[
            'model'=>$user,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            
        ]);
    }
    
    public function actionConfiguracao() {
        $this->layout = '@app/views/layouts/dashboard.php';
        
        return $this->render('configuracao');
    }
    
    public function actionDashboard() {
        $this->layout = '@app/views/layouts/dashboard.php';
        
        return $this->render('dashboard');
    }


}

modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\User;
use app\modules\admin\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;
use app\modules\admin\models\Lead;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['delete', 'index','view','update','create'],
                'rules' => [
                    [
                        'actions' => ['delete', 'index','view','update','create'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['register', 'recovery'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

   

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        $this->layout = '@app/views/layouts/dashboard.php';
        $user = \Yii::$app->user->identity;
        $leads = count(Lead::find()
                ->select('id')
                ->distinct('id')
                ->where(['status'=>10,'Carteira_id'=>$user->carteira_id])
                ->all());
        $usuarios = count(User::find()->where(['status'=>10,'user_create'=>Yii::$app->user->identity->id])->all());
        
        return $this->render('view', [
                    'model' => $this->findModel($id),
                    'usuarios'=>$usuarios,
                    'leads'=>$leads
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionRegister() {
        $model = new User();

        if ($model->load(Yii::$app->request->post())) {
            $model->setPassword($model->passwordHash);
            $model->generatePasswordResetToken();
            $model->generateAuthKey();
            $model->data_create = date('Y-m-d H:i:s');
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Registro realizado com sucesso.');
                return $this->redirect(['default/index']);
            } else {
                Yii::$app->session->setFlash('error', 'Erro no registro.');
                return $this->redirect(['default/index']);
            }
        } else {

            return $this->render('register', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $status = '';
        if($model->status)
        {
           $model->status = 0;
           $status = 'excluido';
        }
        else
        {
           $model->status = 10; 
           $status = 'reativado';
        }
        
        if (!$model->save()) {
            ddd($model->getErrors());
        }
        if($model->id == \Yii::$app->user->identity->id)
        {
            Yii::$app->session->setFlash('success', "Conta excluida com sucesso.");
            Yii::$app->user->logout();
            return $this->redirect(['default/index']);
        }
        else
        {
            Yii::$app->session->setFlash('success', "Usuário {$status} com sucesso.");
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionRecovery($email = null) {

        $model = new User;

        if (Yii::$app->request->post()) {

            $post = Yii::$app->request->post()['User'];

            $model = User::findByEmail($post['email']);
            if (!$model) {
                $model = new User;
                Yii::$app->session->setFlash('error', 'Usuário não encontrado.');
                return $this->render('recovery', [
                            'model' => $model,
                ]);
            }

            $alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890';
            $pass = []; //remember to declare $pass as an array
            $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
            for ($i = 0; $i < 8; $i++) {
                $n = rand(0, $alphaLength);
                $pass[] = $alphabet[$n];
            }

            $model->setPassword(implode($pass));
            if (!$model->save()) {
                ddd($model->getErrors());
            }

            Yii::$app->mailer->compose()
                    ->setFrom('servicos.ti@grupostudio.com.br')
                    ->setTo($model->email)
                    ->setSubject('Sua senha nova é: ' . implode($pass))
                    ->send();
            Yii::$app->session->setFlash('success', 'Senha enviada para seu e-mail.');
            return $this->redirect(['default/index']);
        }

        return $this->render('recovery', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $this->layout = '@app/views/layouts/dashboard.php';
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post())) {
            
            $model->data_update = date('Y-m-d H:i:s');
            $data = date('d-m-o_H-i-s');
            if (!file_exists('images/foto_usuario')) {
                $path = 'images/foto_usuario';
                FileHelper::createDirectory($path);
            } else {
                $path = 'images/foto_usuario';
            }
            
            $arquivo = UploadedFile::getInstance($model, 'arquivo');
            if ($arquivo) {
                $valida_nome = explode('.', $arquivo->name);

                $arquivo->name = $data . '.' . end($valida_nome);
                $model->foto = $arquivo->name;

                if ($arquivo->saveAs($path . '/' . $arquivo->name)) {
                    if ($model->save()) {
                        Yii::$app->session->setFlash('success', 'Atualizado com sucesso.');
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'Houve um problema ao salvar.');
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Atualizado com sucesso.');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }
    
    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionCreate($id) {
        $this->layout = '@app/views/layouts/dashboard.php';
        $model = new User;
        
        if ($model->load(Yii::$app->request->post())) {
            
            $model->setPassword($model->passwordHash);
            $model->generatePasswordResetToken();
            $model->generateAuthKey();
            $model->data_update = date('Y-m-d H:i:s');
            $model->data_create = date('Y-m-d H:i:s');
            $model->user_create = \Yii::$app->user->identity->id;
            
            $data = date('d-m-o_H-i-s');
            if (!file_exists('images/foto_usuario')) {
                $path = 'images/foto_usuario';
                FileHelper::createDirectory($path);
            } else {
                $path = 'images/foto_usuario';
            }
            
            $arquivo = UploadedFile::getInstance($model, 'arquivo');
            if ($arquivo) {
                $valida_nome = explode('.', $arquivo->name);

                $arquivo->name = $data . '.' . end($valida_nome);
                $model->foto = $arquivo->name;

                if ($arquivo->saveAs($path . '/' . $arquivo->name)) {
                    if ($model->save()) {
                        Yii::$app->session->setFlash('success', 'Criado com sucesso.');
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } else {
                    Yii::$app->session->setFlash('error', 'Houve um problema na criação.');
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Criado com sucesso.');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);

modules/admin/views/psa/_footer.php
<footer class="main-footer">
    <div class="pull-right d-none d-sm-inline-block">
        <ul class="nav nav-primary nav-dotted nav-dot-separated justify-content-center justify-content-md-end">
            <li class="nav-item">
                <a class="nav-link" href="index.php?r=site/faq">FAQ</a>
            </li>
        </ul>
    </div>
    &copy; 2018 <a href="">PSA Matriculas</a>.
</footer>

modules/admin/views/psa/_header.php
<header class="main-header">
    <a href="" class="logo">
        <b class="logo-mini">
<!--            <span class="light-logo"><img src="../../images/gsn_logo.png" alt="logo"></span>
            <span class="dark-logo"><img src="../../images/gsn_logo.png" alt="logo"></span>-->
        </b>
        <span class="logo-lg">
<!--            <img src="../../minimalliteadmin/images/logo-light-text.png" alt="logo" class="light-logo">
            <img src="../../minimalliteadmin/images/logo-dark-text.png" alt="logo" class="dark-logo">-->
        </span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
<!--                <li class="search-box">
                    <a class="nav-link hidden-sm-down" href="javascript:void(0)"><i class="mdi mdi-magnify"></i></a>
                    <form class="app-search" style="display: none;">
                        <input type="text" class="form-control" placeholder="Pesquisar"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>		-->
                <li style="list-style-type: disc;color:transparent">
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-cog fa-spin"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

modules/admin/views/psa/_menuleft.php
<?php 
    use app\modules\admin\models\User;
    use yii\bootstrap\Html;
    $model = User::findOne(Yii::$app->user->identity->id);
    $nome = explode(' ',$model->username);
?>


<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li class="user-profile treeview">
                <a href="">
                    <img src="<?= '../../minimalliteadmin/images/user5-128x128.jpg'?>" alt="user">
                    <span style="text-transform: capitalize;"><?=  (isset($nome[0]))?$nome[0]:"";?></span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-right pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <?php Html::a('<i class="fa fa-user mr-5"></i>Minha conta',['user/view','id'=>$model->id])?>
                    </li>
                    <li>
                        <?= Html::a('<i class="fa fa-circle-thin"></i>Inicio',['psa/index'])?>
                    </li>
                    <?php if($model->id > 10):?>
                     <li>
                        <?= Html::a('<i class="fa fa-circle-thin"></i>Matricular',['disciplina/index'])?>
                    </li>
                    <li>
                        <?= Html::a('<i class="fa fa-circle-thin"></i>Comprovante Matricula',['disciplina-aluno-turma/comprovante_matricula','id'=>\Yii::$app->user->identity->id], ['target'=>'_blank'])?>
                    </li>
                     <?php endif; ?>
                     <?php if($model->id < 10):?>
                     <li>
                        <?= Html::a('<i class="fa fa-circle-thin"></i>Relatório Ocupação',['disciplina/relatorio_ocup'])?>
                    </li>
                     <li>
                        <?= Html::a('<i class="fa fa-circle-thin"></i>Relatório Credito',['disciplina/relatorio_alunocred'])?>
                    </li>
                     <li>
                        <?= Html::a('<i class="fa fa-circle-thin"></i>Relatório Disciplina',['disciplina/relatorio_alunodisci'])?>
                    </li>
                        <?php endif; ?>          
                    <li><?= Html::a('<i class="fa fa-power-off mr-5"></i> Sair', ['default/logout']) ?></li>
                </ul>
            </li>
            
        </ul>
    </section>
</aside>


                 

modules/admin/views/psa/_menuright.php
<aside class="control-sidebar control-sidebar-dark">
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    </ul>
    <div class="tab-content">
        <div class="tab-pane" id="control-sidebar-home-tab">
        </div>

    </div>
</aside>
<div class="control-sidebar-bg"></div>

modules/admin/views/psa/configuracao.php
<?php

use yii\helpers\Html;
use app\models\Helper;
$this->title = "Configurações Gerais";
?>
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Configurações
            <small>Gerais</small>
        </h1>
        <ol class="breadcrumb">
            <!--<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Início</a></li>-->
        </ol>
    </section>

    <section class="content">
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <div class="form-group">
                        <?= Html::a('Usuários', ['user/index'], ['class' => 'btn btn-sm btn-dark','style'=>'margin: 3px 0;']) ?>
                        <?= Html::a('Carteira', ['carteira/index'], ['class' => 'btn btn-sm btn-danger','style'=>'margin: 3px 0;']) ?>
                        <?php Html::a('Compromisso Grupo', ['compromisso-grupo/index'], ['class' => 'btn btn-sm btn-warning','style'=>'margin: 3px 0;']) ?>
                        <?php Html::a('Compromisso Status', ['compromisso-status/index'], ['class' => 'btn btn-sm btn-warning','style'=>'margin: 3px 0;']) ?>
                        <?php Html::a('Compromisso Tipo', ['compromisso-tipo/index'], ['class' => 'btn btn-sm btn-warning','style'=>'margin: 3px 0;']) ?>
                        <?php Html::a('Lead Situação', ['lead-situacao/index'], ['class' => 'btn btn-sm btn-success','style'=>'margin: 3px 0;']) ?>
                        <?php Html::a('Lead Status', ['lead-status/index'], ['class' => 'btn btn-sm btn-success','style'=>'margin: 3px 0;']) ?>
                        <?php Html::a('Oportunidade Status', ['oportunidade-status/index'], ['class' => 'btn btn-sm btn-info','style'=>'margin: 3px 0;']) ?>
                        <?php Html::a('Oportunidade Tipo', ['oportunidade-tipo/index'], ['class' => 'btn btn-sm btn-info','style'=>'margin: 3px 0;']) ?>
                        <?= Html::a('Produto', ['produto/index'], ['class' => 'btn btn-sm btn-secondary','style'=>'margin: 3px 0;']) ?>
                        
                    </div>
                    <div class="box-tools pull-right">
                        <!--                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                                        <i class="fa fa-minus"></i></button>
                                                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                                        <i class="fa fa-times"></i></button>-->
                    </div>
                </div>
<!--                <div class="box-body">
                    
                </div>-->
            </div>
        </section>
</div>

modules/admin/views/psa/dashboard.php
<?php

use yii\helpers\Html;
use app\models\Helper;

?>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Criados', 'Oportunidades', 'Leads','Compromissos'],
          ['jan/18', 1000,100,100],
          ['fev/18', 900, 1000,100],
          ['mar/18', 800, 1000,100],
          ['abr/18', 600, 1000,100],
          ['mai/18', 1000, 1000,100],
          ['jun/18', 1200, 1000,100],
          ['jul/18', 800, 1000,100],
          ['ago/18', 100, 1000,100],
          ['set/18', 600, 1000,100],
          ['out/18', 500, 1000,100],
          ['nov/18', 400, 1000,100],
          ['dez/18', 300, 1000,100]
        ]);

        var options = {
          chart: {
            title: 'Criados no ano',
            subtitle: '',
          }
        };

        var chart = new google.charts.Bar(document.getElementById('chart_criados_ano'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
      }
    </script>
<input type="hidden" id="pageurl" value="<?= Yii::$app->urlManager->createUrl(['admin/lead/updateindex']) ?>">
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Dashboard
            <small>Gestão de Contatos</small>
        </h1>
        <ol class="breadcrumb">
            <!--<li c   lass="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Início</a></li>-->
        </ol>
    </section>

    <section class="content">
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <div class="form-group">
                        
                    </div>
                    <div class="box-tools pull-right">
                        <!--                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                                        <i class="fa fa-minus"></i></button>
                                                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                                        <i class="fa fa-times"></i></button>-->
                    </div>
                </div>
                <div class="box-body">
                    <div class="column col-sm-12 col-md-3">
                        <div id="chart_criados_ano" style="width: 600px; height: 400px;"></div>
                    </div>
                </div>
            </div>
        </section>
</div>

modules/admin/views/psa/index.php
<?php

use yii\helpers\Html;
use app\models\Helper;
$this->title = 'Início';
?>
<style>
    .tilt {
        transform: rotate(3deg);
        -moz-transform: rotate(3deg);
        -webkit-transform: rotate(3deg);
    }

    .column {
        float: left;
        padding-bottom: 100px;
    }
    .portlet {
        margin: 0 1em 1em 0;
        padding: 0.3em;
    }
    .portlet-header {
        padding: 0.2em 0.3em;
        margin-bottom: 0.5em;
        position: relative;
    }
    .portlet-toggle {
        position: absolute;
        top: 50%;
        right: 0;
        margin-top: -8px;
    }
    .portlet-content {
        padding: 0.4em;
    }
    .portlet-placeholder {
        border: 1px dotted black;
        margin: 0 1em 1em 0;
        height: 50px;
    }
</style>
<input type="hidden" id="pageurl" value="<?= Yii::$app->urlManager->createUrl(['admin/lead/updateindex']) ?>">
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Início
            <small>PSA Matriculas</small>
        </h1>
        <ol class="breadcrumb">
            <!--<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Início</a></li>-->
        </ol>
    </section>

    <section class="content">
        <section class="content">
            <div class="box">
                <div class="box-header with-border">
                    <div class="form-group">
                        <?php
                            if(Yii::$app->user->identity->id != 1){
                                echo Html::a('Matricula',['disciplina/index'],['class'=>'btn btn-md btn-success']);
                            }
                            else{
                                echo Html::a('Relatorio %',['disciplina/relatorio_ocup'],['class'=>'btn btn-md btn-success','target'=>'_blank']);
                                echo ' '.Html::a('Aluno Disciplina',['disciplina/relatorio_alunodisci'],['class'=>'btn btn-md btn-success','target'=>'_blank']);
                                echo ' '.Html::a('Aluno Crédito Total',['disciplina/relatorio_alunocred'],['class'=>'btn btn-md btn-success','target'=>'_blank']);
                            }
                        ?>
                    </div>
                    <div class="box-tools pull-right">
                        <!--                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                                        <i class="fa fa-minus"></i></button>
                                                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                                        <i class="fa fa-times"></i></button>-->
                    </div>
                </div>
                <div class="box-body">
                    <div class="column col-sm-12 col-md-3">
                    
                    </div>
                </div>
            </div>
        </section>
</div>